#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2026 Atsushi Noda
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parent
CONFIG = ROOT / "config.toml"
OUTPUT = ROOT / "src" / "client_config.py"


def main() -> int:
    if not CONFIG.exists():
        raise SystemExit(f"config.toml not found: {CONFIG}")
    with CONFIG.open("rb") as f:
        cfg = tomllib.load(f)
    client = cfg.get("client", {})
    host = str(client.get("server_host", "127.0.0.1"))
    voice_port = int(client.get("voice_port", 50000))
    schedule_port = int(client.get("schedule_port", 8766))
    text = f'''# Auto-generated by generate_client_config.py.\n# Do not edit this file directly.\nAI_HOST = {host!r}\nVOICE_PORT = {voice_port}\nSCHEDULE_PORT = {schedule_port}\n'''
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"written: {OUTPUT}")
    print(f"AI_HOST={host} VOICE_PORT={voice_port} SCHEDULE_PORT={schedule_port}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
